import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";
import "@rainbow-me/rainbowkit/styles.css";
import { ethers } from "ethers";
import {
  getDefaultWallets,
  RainbowKitProvider,
  ConnectButton,
  darkTheme
} from "@rainbow-me/rainbowkit";
import CustomConnectButton from '../components/CustomConnectButton';

import { chain, configureChains, createClient, WagmiConfig } from "wagmi";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";


import "./../public/assets/css/animate.min.css";
import "./../public/assets/css/aos.css";
import "./../public/assets/css/bootstrap.min.css";
import "./../public/assets/css/default.css";
import "./../public/assets/css/fontawesome-all.min.css";
import "./../public/assets/css/magnific-popup.css";
import "./../public/assets/css/odometer.css";
import "./../public/assets/css/responsive.css";
import "./../public/assets/css/slick.css";
import "./../public/assets/css/style.css";

function MyApp({ Component, pageProps }) {
  const { chains, provider } = configureChains(
    [chain.mainnet, chain.polygonMumbai, chain.optimism, chain.arbitrum],
    [
      alchemyProvider({ alchemyId: process.env.REACT_APP_ALCHEMY_ID }),
      publicProvider(),
    ]
  );

  const { connectors } = getDefaultWallets({
    appName: "My RainbowKit App",
    chains,
  });

  const wagmiClient = createClient({
    autoConnect: true,
    connectors,
    provider,
  });

  return (
    <div styles={{background: 'black'}}>
       <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider theme={darkTheme()} chains={chains}>
        <header className="third-header-bg home-five-header">
            <div className="bg"></div>
            <div className="container custom-container">
                <div className="header-top-area t-header-top-area d-none d-lg-block">
                    <div className="row">
                        <div className="col-sm-6">
                            <div className="header-top-social">
                                <ul>
                                    <li>Follow</li>
                                    <li><a href="https://mobile.twitter.com/gg_quest_gg"><i className="fab fa-twitter"></i></a></li>
                                    <li><a href="https://mobile.twitter.com/gg_quest_gg"><i className="fab fa-discord"></i></a></li>
                                    <li><a href="https://mobile.twitter.com/gg_quest_gg"><i className="fab fa-telegram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div className="col-sm-6">
                            <div className="header-top-login">
                                <ul>
                                <CustomConnectButton />
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="sticky-header">
                <div className="container custom-container">
                    <div className="row">
                        <div className="col-12">
                            <div className="main-menu menu-style-two">
                                <nav>
                                    <div className="logo d-block d-lg-none">
                                        <a href="index-5.html"><img src="./assets/img/logo/logo.png" alt="Logo"/></a>
                                    </div>
                                    <div className="navbar-wrap d-none d-lg-flex">
                                        <ul className="left">
                                          <li><Link href="/">Quests</Link> </li>
                                          <li><Link href="/leaderboard">leaderboard</Link></li>
                                        </ul>
                                        <div className="logo">
                                            <a href="index-3.html"><img src="./assets/img/logo/h5_logo.png" alt="Logo"/></a>
                                        </div>
                                        <ul className="right">
                                            <li><Link href="/stats">My stats</Link></li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                            <div className="mobile-menu-wrap d-block d-lg-none">
                                <nav>
                                    <div id="mobile-menu" className="navbar-wrap">
                                        <ul>
                                            <li className="show"><a href="#">Home</a></li>
                                            <li><a href="about-us.html" >About</a></li>
                                            <li><a href="game-overview.html">Overview</a></li>
                                            <li><a href="community.html">Community</a></li>
                                            <li><a href="shop.html">Store</a></li>
                                            <li><a href="#">Blog</a></li>
                                            <li><a href="contact.html">contact</a></li>
                                        </ul>
                                    </div>
                                </nav>
                            </div>
                            <div className="mobile-menu"></div>
                        </div>

                    </div>
                </div>
            </div>
            <div className="header-bottom-bg"></div>
        </header>
        

        <Component {...pageProps} />

      </RainbowKitProvider>
    </WagmiConfig>
        
    </div>
    </div>
  )
}

export default MyApp
